package com.aicard.app.ui.theme

import androidx.compose.ui.graphics.Color

// ===== Light · 暖琥珀 brand =====
val md_primary = Color(0xFF86550A)
val md_onPrimary = Color(0xFFFFFFFF)
val md_primaryContainer = Color(0xFFFFDFAE)
val md_onPrimaryContainer = Color(0xFF2B1700)
val md_secondary = Color(0xFF715D41)
val md_onSecondary = Color(0xFFFFFFFF)
val md_secondaryContainer = Color(0xFFFCE0BD)
val md_onSecondaryContainer = Color(0xFF271B07)
val md_tertiary = Color(0xFF7E5260)
val md_onTertiary = Color(0xFFFFFFFF)
val md_tertiaryContainer = Color(0xFFFFD9DF)
val md_onTertiaryContainer = Color(0xFF31101B)
val md_background = Color(0xFFFFFBF7)
val md_onBackground = Color(0xFF1E1B16)
val md_surface = Color(0xFFFFFBF7)
val md_onSurface = Color(0xFF1E1B16)
val md_surfaceVariant = Color(0xFFEEE0CC)
val md_onSurfaceVariant = Color(0xFF4E4639)
val md_outline = Color(0xFF807668)
val md_error = Color(0xFFBA1A1A)
val md_onError = Color(0xFFFFFFFF)
val md_errorContainer = Color(0xFFFFDAD6)
val md_onErrorContainer = Color(0xFF410002)

// Light · M3 tonal surface 层级（2023 角色，卡片/面板层次的关键）
val md_surfaceDim = Color(0xFFE4D9CB)
val md_surfaceBright = Color(0xFFFFFBF7)
val md_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_surfaceContainerLow = Color(0xFFFFF8F2)
val md_surfaceContainer = Color(0xFFFCF0E4)
val md_surfaceContainerHigh = Color(0xFFF6EADC)
val md_surfaceContainerHighest = Color(0xFFF0E4D6)
val md_outlineVariant = Color(0xFFD5C6B0)
val md_inverseSurface = Color(0xFF33302A)
val md_inverseOnSurface = Color(0xFFF7EFE7)
val md_inversePrimary = Color(0xFFFFB957)
val md_scrim = Color(0xFF000000)

// ===== Dark · 暖琥珀 brand =====
val md_primary_dark = Color(0xFFFFB957)
val md_onPrimary_dark = Color(0xFF482900)
val md_primaryContainer_dark = Color(0xFF673E00)
val md_onPrimaryContainer_dark = Color(0xFFFFDFAE)
val md_secondary_dark = Color(0xFFDEC4A4)
val md_onSecondary_dark = Color(0xFF3E2E17)
val md_secondaryContainer_dark = Color(0xFF57442B)
val md_onSecondaryContainer_dark = Color(0xFFFCE0BD)
val md_tertiary_dark = Color(0xFFF0B8C4)
val md_onTertiary_dark = Color(0xFF4A2530)
val md_tertiaryContainer_dark = Color(0xFF643B47)
val md_onTertiaryContainer_dark = Color(0xFFFFD9DF)
val md_background_dark = Color(0xFF17130C)
val md_onBackground_dark = Color(0xFFEEE0CC)
val md_surface_dark = Color(0xFF17130C)
val md_onSurface_dark = Color(0xFFEEE0CC)
val md_surfaceVariant_dark = Color(0xFF4E4639)
val md_onSurfaceVariant_dark = Color(0xFFD1C4B0)
val md_outline_dark = Color(0xFF9A8F7E)
val md_error_dark = Color(0xFFFFB4AB)
val md_onError_dark = Color(0xFF690005)
val md_errorContainer_dark = Color(0xFF93000A)
val md_onErrorContainer_dark = Color(0xFFFFDAD6)

// Dark · M3 tonal surface 层级
val md_surfaceDim_dark = Color(0xFF17130C)
val md_surfaceBright_dark = Color(0xFF3A342B)
val md_surfaceContainerLowest_dark = Color(0xFF120D07)
val md_surfaceContainerLow_dark = Color(0xFF201A11)
val md_surfaceContainer_dark = Color(0xFF241E15)
val md_surfaceContainerHigh_dark = Color(0xFF2F281E)
val md_surfaceContainerHighest_dark = Color(0xFF3A3329)
val md_outlineVariant_dark = Color(0xFF4E4639)
val md_inverseSurface_dark = Color(0xFFEEE0CC)
val md_inverseOnSurface_dark = Color(0xFF1E1B16)
val md_inversePrimary_dark = Color(0xFF86550A)
val md_scrim_dark = Color(0xFF000000)
